### ISSUE TITLE
Frama Data randomly stops updating

### ISSUE THREAD

**Issue by Loemnk** [Alchemy-Meister/TekkenBot#13]
This has been an issue since the start of season 3, but since I couldn't find anyone talk about this, I thought I was the only one with the problem.

Anyways, TekkenBotPrime randomly stops updating the frame numbers, meaning the program essentially freezes and requires a restart to work again.
Sometimes just starting a new match will work as well, but this is rather rare.
There is no error message whatsoever.
I am not able to consistently recreate the issue, so I couldn't exactly say what is causing it, but sometimes it will freeze after 5 minutes and sometimes after an hour.

The settings are all on default except the Auto-hide function which I untick everytime I start TBP so the framedata window does not disappear.

I do tab out of the game a lot to look things up, just to describe my behavior when running Tekken  7.

Should it matter: I am using Full Screen mode for Tekken 7 and have the TekkenBotPrime window displayed on separate monitor.

**Comment by Alchemy-Meister** [comment]
Could you try this pre-release and confirm if it still happens?
https://github.com/Alchemy-Meister/TekkenBot/releases/tag/0.1.19b1

**Comment by Loemnk** [comment]
I've been testing this all day yesterday and with the build you posted, this does not seem to be an issue anymore
No freezing anymore :)

**Comment by Alchemy-Meister** [comment]
Good to know. I will release this build soon. But just to confirm the freeze is gone for good, could you test it for a couple of days more and report back?

That would be much appreciated.

**Comment by Loemnk** [comment]
Ofc, will do

**Comment by Loemnk** [comment]
Okay, I must have been lucky yesterday, because it seems to have frozen again :(
But the program is given me an exception this time:

Exception in Tkinter callback

ValueError: 8704 is not a valid InputAttack

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tkinter\__init__.py", line 749, in callit
  File "tekken\launcher.py", line 77, in __update_launcher
  File "tekken_game_state.py", line 74, in update
  File "tekken\process_io_manager.py", line 90, in update
  File "tekken\game_reader.py", line 432, in get_updated_state
  File "tekken\game_reader.py", line 615, in initialize_bots
  File "tekken\bot_snapshot.py", line 75, in __init__
  File "e:\portable_dev_tools\python\python3_7\lib\enum.py", line 310, in __call__
  File "e:\portable_dev_tools\python\python3_7\lib\enum.py", line 564, in __new__
  File "e:\portable_dev_tools\python\python3_7\lib\enum.py", line 548, in __new__
  File "e:\portable_dev_tools\python\python3_7\lib\enum.py", line 577, in _missing_
ValueError: 8704 is not a valid InputAttack

**Comment by Alchemy-Meister** [comment]
Sorry for the late response.
That's a duplicated #10 issue that tends to happen online.

I don't know the meaning of those new values yet, so I have implemented a quick solution that ignores those values and treats them as *Null*.

Feel free to try it this works for you (I haven't had time to test it myself):

https://github.com/Alchemy-Meister/TekkenBot/releases/tag/0.1.19b2

**Comment by Loemnk** [comment]
Thx, will try it out and report back

**Comment by Loemnk** [comment]
So I've been testing this for the last week now and I think this time it's safe to say it doesn't freeze anymore.
Ofc, should it happen again I will report it here again. 
Thx for the effort you put into this :)

**Comment by Alchemy-Meister** [comment]
Thank you, I'll close this and #10 then. Feel free to reopen them if it happens again.
