### ISSUE TITLE
Update for Season 4?

### ISSUE THREAD

**Issue by int3r** [Alchemy-Meister/TekkenBot#19]
Just wondering if there's gonna be an update for S4.

Thanks for all the hard work you've done! :)

**Comment by Alchemy-Meister** [comment]
Sure,

Please check if this build works for you, and if it does, please reply back so that make it public for everyone else ;)

https://github.com/Alchemy-Meister/TekkenBot/releases/tag/0.1.24

**Comment by int3r** [comment]
My work day isn't over yet, so I can't do a fully proper test, but the new version launches correctly with no errors, and the frame data and punish alarm both worked for the 30 seconds I tested in training mode 👍 

Thanks a ton for the update! Will let you know if any bugs crop up :)

**Comment by int3r** [comment]
Small thing I noticed: in the Tekken Bot menu -> Preferences -> Settings button doesn't do anything (not sure if that's supposed to be disabled).

Editing things in the settings.ini still seems to save them appropriately.

**Comment by Alchemy-Meister** [comment]
> My work day isn't over yet, so I can't do a fully proper test, but the new version launches correctly with no errors, and the frame data and punish alarm both worked for the 30 seconds I tested in training mode 👍
> 
> Thanks a ton for the update! Will let you know if any bugs crop up :)

Settings is just a placeholder, not implemented at the moment as explained in #18

Thanks for the testing, I can close this issue now.
