### ISSUE TITLE
Don't remove framedata window when not in the match

### ISSUE THREAD

**Issue by KulaGGin** [Alchemy-Meister/TekkenBot#9]
I play fullscreen and have 2 monitors.
I use it as draggable window. When I change characters in practice mode(simple select), it removes draggable window when it changes characters and restarts the level. Then when practice mode starts again, framedata window comes back and it minimizes my game.
Probable solution: add a menu to allow us to choose, so draggable window doesn't close when match ends.

**Comment by Alchemy-Meister** [comment]
There's already an menu for that. Uncheck the *overlay > auto-hide* option to makes the overlays always visible. You can also set *overlay_automatic_hide = False* in *.\data\settings.ini* to make this selection the default behavior on TBP startup.
![image](https://user-images.githubusercontent.com/5882817/64993724-0f6ed200-d8d7-11e9-9f7f-40cdda74c935.png)
